# Generated by Django 4.1.7 on 2023-03-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSystem', '0002_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
